project:
  type: website
  output-dir: docs

website:
  title: "Iris Carnahan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - hobbies.qmd
      - resume.qmd

# supplying just one theme ("yeti")
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full



